# Generated by Django 3.1.8 on 2021-04-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='port_groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=250)),
                ('port', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='server_groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=250)),
                ('ip', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='tests_to_run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=250)),
                ('source_ip', models.CharField(max_length=250)),
                ('source_port', models.CharField(max_length=250)),
                ('dest_ip', models.CharField(max_length=250)),
                ('dest_port', models.CharField(max_length=250)),
            ],
        ),
    ]
